/**
 * TODO add locale logic of algorithim to combine key_parse with key_app generated by install app
 */
use aes_gcm::{
    aead::{Aead, AeadCore, KeyInit, OsRng},
    Aes256Gcm,
};
use base64::{engine::general_purpose::STANDARD, Engine as _};
use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};

#[derive(Debug, Clone)]
pub struct Crypt {
    pub original_value: String,
    pub value: String,
    pub key_parse: String,
    pub created_at: DateTime<Utc>,
}

pub trait CryptTrait: Sized {
    fn new(original_value: String, key_parse: String) -> Self;
    fn decrypt(encrypted_value: &str, key_parse: String) -> Result<Self, String>;
}

impl CryptTrait for Crypt {
    fn new(original_value: String, key_parse: String) -> Self {
        let created_at = Utc::now();

        let mut hasher = Sha256::default();
        hasher.update(key_parse.as_bytes());
        let key_bytes = hasher.finalize().to_vec();

        let cipher =
            Aes256Gcm::new_from_slice(&key_bytes).expect("Falha ao inicializar cipher AES-GCM");

        let nonce = Aes256Gcm::generate_nonce(&mut OsRng);

        let value_to_encrypt = format!(
            "{}|||TIMESTAMP|||{}",
            original_value,
            created_at.timestamp()
        );

        let encrypted_value = cipher
            .encrypt(&nonce, value_to_encrypt.as_bytes())
            .expect("Falha ao criptografar valor");

        let mut combined = nonce.to_vec();
        combined.extend_from_slice(&encrypted_value);
        let value = STANDARD.encode(combined);

        Self {
            original_value,
            value,
            key_parse,
            created_at,
        }
    }

    fn decrypt(encrypted_value: &str, key_parse: String) -> Result<Self, String> {
        let combined = STANDARD
            .decode(encrypted_value)
            .map_err(|e| format!("Falha ao decodificar base64: {}", e))?;

        if combined.len() < 12 {
            return Err("Dados criptografados inválidos".to_string());
        }

        let nonce_bytes = &combined[..12];
        let encrypted_data = &combined[12..];

        let mut hasher = Sha256::default();
        hasher.update(key_parse.as_bytes());
        let key_bytes = hasher.finalize().to_vec();

        let cipher = Aes256Gcm::new_from_slice(&key_bytes)
            .map_err(|e| format!("Falha ao inicializar cipher: {}", e))?;

        let nonce = aes_gcm::Nonce::from_slice(nonce_bytes);

        let decrypted_bytes = cipher
            .decrypt(nonce, encrypted_data)
            .map_err(|e| format!("Falha ao descriptografar: {}", e))?;

        let decrypted_value = String::from_utf8(decrypted_bytes)
            .map_err(|e| format!("Falha ao converter para string: {}", e))?;

        let (original_value, created_at) = {
            if let Some((value_part, timestamp_part)) =
                decrypted_value.split_once("|||TIMESTAMP|||")
            {
                let original_value = value_part.to_string();
                let created_at = timestamp_part
                    .parse::<i64>()
                    .map_err(|e| format!("Falha ao fazer parse do timestamp: {}", e))?;
                let created_at = DateTime::from_timestamp(created_at, 0)
                    .ok_or_else(|| "Timestamp inválido".to_string())?;
                (original_value, created_at)
            } else {
                return Err("Formato de dados descriptografados inválido".to_string());
            }
        };

        Ok(Self {
            original_value,
            key_parse,
            created_at,
            value: encrypted_value.to_string(),
        })
    }
}
